### ISSUE TITLE
      ModuleNotFoundError: No module named 'former3d.net3d.former_v1'

### ISSUE THREAD

**Issue by passingdragon** [alibaba-damo-academy/former3d#9]
why this error，I success pip install e .

`
(former3d37) zcl@gengjing:/DATA/zcl/former3d-main$ python scripts/train.py --config config.yml --gpus [0,1,2]
Traceback (most recent call last):
  File "scripts/train.py", line 11, in <module>
    from former3d import data, lightningmodel
  File "/DATA/zcl/myConda/miniconda/envs/former3d37/lib/python3.7/site-packages/former3d/lightningmodel.py", line 9, in <module>
    from former3d import sdfformer
  File "/DATA/zcl/myConda/miniconda/envs/former3d37/lib/python3.7/site-packages/former3d/sdfformer.py", line 9, in <module>
    from former3d.net3d.former_v1 import Former3D as backbone3d
ModuleNotFoundError: No module named 'former3d.net3d.former_v1'

`

**Comment by passingdragon** [comment]
The environment was not configured successfully according to readme so python3.7 was used

**Comment by weihaosky** [comment]
This may be a Python path configuration problem.

**Comment by passingdragon** [comment]
I add python interpreter search path to solve this bug.Thanks.
`
import sys
sys.path.append('/DATA/zcl/former3d-main')
`
